## <font color=red>Exercise</font>

1. Write a very brief extremely high level description of how you will implement the bubble sort algorithm. Use natural language (no code).

2. Write pseudocode for the bubble sort algorithm.

3. Write a function that implements the bubble sort algorithm on an input array and use it to sort the list of items below.

In [1]:
import numpy as np
items = np.random.randint(0, 10, (20,))
items

array([6, 2, 9, 6, 8, 1, 8, 6, 8, 4, 1, 8, 3, 0, 2, 5, 2, 7, 5, 6])

In [2]:
# WHILE list not sorted:
#     FOR each pair of items in list:
#         IF items out of order:
#             swap the pair of items
#     IF we didn't swap any items:
#         list is sorted!!!

def bubbleSort(items):
    numItems = len(items)
    isSorted = False
    while not isSorted:
        isSorted = True  # assume sorted unless we have to swap during this loop
        for i in range(numItems-1):
            if items[i+1] < items[i]:  # items out of order
                items[i], items[i+1] = items[i+1], items[i]  # swap items
                isSorted = False  # we swapped, so we're not sorted yet

In [3]:
bubbleSort(items)  # sort items
items

array([0, 1, 1, 2, 2, 2, 3, 4, 5, 5, 6, 6, 6, 6, 7, 8, 8, 8, 8, 9])

## <font color=red>Exercise</font>

1. Write a very brief description of how you will implement the insertion sort algorithm.

2. Write pseudocode for the insertion sort algorithm.

3. Write a function that implements the insertion sort algorithm on an input array and use it to sort the list of items below.

In [4]:
import numpy as np
items = np.random.randint(0, 10, (20,))
items

array([3, 0, 7, 1, 5, 9, 5, 5, 0, 8, 4, 2, 9, 4, 7, 2, 0, 5, 5, 2])

In [5]:
def insertionSort(items):
    for i in range(1, len(items)):
        for j in range(i, 0, -1):
            if items[j-1] > items[j]:
                items[j-1], items[j] = items[j], items[j-1]
            else:
                break

In [6]:
insertionSort(items)
items

array([0, 0, 0, 1, 2, 2, 2, 3, 4, 4, 5, 5, 5, 5, 5, 7, 7, 8, 9, 9])